spring:
  application:
    name: alertbuyers
  datasource:
    url: jdbc:h2:mem:alertbuyers;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true



weatherClient:
  strategy: weatherApiClient

notification:
  strategy: mailTrapSender